version: '3.8'

services:
  apache-php:
    image: apache-pdo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - D:/Installation/xampp/htdocs/event-management/src:/var/www/html
    ports:
      - '80:80'
    networks:
      - app-network

  mysql:
    image: mysql
    volumes:
      - D:/Jester_Blog/Dev_Project/suthikawong/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pw
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
